export const ActionType = {
  /* GET_NOTES */
  GET_NOTES_START: "GET_NOTES_START",
  GET_NOTES_SUCCEED: "GET_NOTES_SUCCEED",
  GET_NOTES_FAIL: "GET_NOTES_FAIL",
  /* SUBMIT_NOTE */
  SUBMIT_NOTE_START: "SUBMIT_NOTE_START",
  SUBMIT_NOTE_SUCCEED: "SUBMIT_NOTE_SUCCEED",
  SUBMIT_NOTE_FAIL: "SUBMIT_NOTE_FAIL",
  /* NEW_EMPTY_NOTE */
  NEW_EMPTY_NOTE: "NEW_EMPTY_NOTE",
  /* EDIT_NOTE */
  EDIT_NOTE: "EDIT_NOTE",
  /* DELETE_NOTE */
  DELETE_NOTE_START: "DELETE_NOTE_START",
  DELETE_NOTE_SUCCEED: "DELETE_NOTE_SUCCEED",
  DELETE_NOTE_FAIL: "DELETE_NOTE_FAIL",
  /* DELETE_UNSAVED_NOTE */
  DELETE_UNSAVED_NOTE: "DELETE_UNSAVED_NOTE",
  /* CHANGE_NOTE_IDX_ON_EDIT */
  CHANGE_NOTE_IDX_ON_EDIT: "CHANGE_NOTE_IDX_ON_EDIT"
} as const;
