export const GET_NOTES_START = 'GET_NOTES_START';
export const GET_NOTES_SUCCEED = 'GET_NOTES_SUCCEED';
export const GET_NOTES_FAIL = 'GET_NOTES_FAIL';

export const UPDATE_NOTE_START = 'UPDATE_NOTE_START';
export const UPDATE_NOTE_SUCCEED = 'UPDATE_NOTE_SUCCEED';
export const UPDATE_NOTE_FAIL = 'UPDATE_NOTE_FAIL';
